name: Unit Tests and Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Just
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Java version
        run: java -version

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Chmod
        run: chmod +x ./mvnw

      - name: Run Build using Just
        run: just build

      - name: Check Build Output
        if: success()
        run: echo "Build completed successfully."

      - name: Check Build Output
        if: failure()
        run: echo "Build failed."
